workflows:
  ios-tcc:
    name: iOS - Time Capsule Camera
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "time_capsule_camera/TimeCapsuleCamera.xcworkspace"
        XCODE_SCHEME: "TimeCapsuleCamera"
        IOS_BUNDLE_ID: "com.mkyoung.timecapsulecamera"
      groups:
        - firebase_credentials
        - ios_signing

    scripts:
      - name: Install CocoaPods
        script: |
          cd time_capsule_camera
          pod install

      - name: Force New Cert and Sign
        script: |
          set -e
          
          # 1. Update Bundle ID
          cd time_capsule_camera
          find . -name "project.pbxproj" -exec sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*;/PRODUCT_BUNDLE_IDENTIFIER = $IOS_BUNDLE_ID;/g" {} +
          echo "✅ Bundle ID updated to $IOS_BUNDLE_ID"

          # 2. Initialize Keychain
          keychain initialize

          # 3. ⚡️ FORCE CREATE NEW CERTIFICATE (Modern Command) ⚡️
          # This command creates a BRAND NEW certificate and saves the private key.
          app-store-connect certificates create --type IOS_DISTRIBUTION \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

          # 4. Fetch Profiles
          # We tell it to ignore old stuff and just use what we made.
          app-store-connect fetch-signing-files "$IOS_BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
          
          # 5. Apply Settings
          keychain add-certificates
          xcode-project use-profiles

      - name: Build archive
        script: |
          set -euo pipefail
          
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/TimeCapsuleCamera.xcarchive" \
            clean archive

      - name: Export IPA
        script: |
          set -euo pipefail
          EXPORT_PATH="$CM_BUILD_DIR/ipa"
          mkdir -p "$EXPORT_PATH"

          # Generate export options
          xcode-project export-options-plist \
            --bundle-id "$IOS_BUNDLE_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --output exportOptions.plist

          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/TimeCapsuleCamera.xcarchive" \
            -exportPath "$EXPORT_PATH" \
            -exportOptionsPlist exportOptions.plist

      - name: Publish to Firebase App Distribution
        script: |
          npm install -g firebase-tools
          firebase appdistribution:distribute "$CM_BUILD_DIR/ipa/TimeCapsuleCamera.ipa" \
            --app "1:413771745824:ios:3203939db870ae52e08a45" \
            --groups "beta-testers" \
            --token "$FIREBASE_TOKEN"

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
