workflows:
  ios-tcc:
    name: iOS – Time Capsule Camera
    max_build_duration: 120
    # Updated configuration - ready for TestFlight
    environment:
      groups:
        - ios_signing
      vars:
        XCODE_PROJECT: "time_capsule_camera/TimeCapsuleCamera.xcodeproj"
        XCODE_SCHEME: "TimeCapsuleCamera"
        BUNDLE_ID: "com.mkyoung.timecapsulecamera"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mkyoung.timecapsulecamera
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Install Firebase dependencies with CocoaPods
        script: |
          cd time_capsule_camera
          pod install
      - name: Generate retro 80s-90s app icons
        script: |
          # Install Pillow for image generation
          pip3 install --quiet pillow

          # Use Python to generate retro-styled icon sizes
          cd time_capsule_camera/Assets.xcassets/AppIcon.appiconset
          python3 << 'EOF'
          from PIL import Image, ImageDraw, ImageFont
          import json

          # Define all required icon sizes for iPhone
          sizes = [
              ("icon-20@2x.png", 40),
              ("icon-20@3x.png", 60),
              ("icon-29@2x.png", 58),
              ("icon-29@3x.png", 87),
              ("icon-40@2x.png", 80),
              ("icon-40@3x.png", 120),
              ("icon-60@2x.png", 120),
              ("icon-60@3x.png", 180),
              ("icon-1024.png", 1024)
          ]

          # Generate retro 80s-90s styled icons
          for filename, size in sizes:
              # Create gradient background with retro colors
              img = Image.new('RGB', (size, size))
              draw = ImageDraw.Draw(img)

              # Retro gradient - purple to pink to orange (sunset vibes)
              for y in range(size):
                  # Calculate color based on position
                  ratio = y / size
                  if ratio < 0.33:
                      # Purple to pink
                      r = int(147 + (255 - 147) * (ratio * 3))
                      g = int(51 + (105 - 51) * (ratio * 3))
                      b = int(165 + (180 - 165) * (ratio * 3))
                  elif ratio < 0.66:
                      # Pink to orange
                      r = 255
                      g = int(105 + (150 - 105) * ((ratio - 0.33) * 3))
                      b = int(180 - (180 - 100) * ((ratio - 0.33) * 3))
                  else:
                      # Orange to yellow
                      r = 255
                      g = int(150 + (200 - 150) * ((ratio - 0.66) * 3))
                      b = int(100 - (100 - 50) * ((ratio - 0.66) * 3))

                  draw.line([(0, y), (size, y)], fill=(r, g, b))

              # Draw retro camera icon in center
              center_x = size // 2
              center_y = size // 2
              cam_size = int(size * 0.4)

              # Camera body (white with shadow)
              body_rect = [
                  center_x - cam_size//2,
                  center_y - cam_size//3,
                  center_x + cam_size//2,
                  center_y + cam_size//3
              ]

              # Shadow
              shadow_rect = [x + int(size * 0.02) for x in body_rect]
              draw.rounded_rectangle(shadow_rect, radius=int(size*0.05), fill=(0, 0, 0, 80))

              # Main body
              draw.rounded_rectangle(body_rect, radius=int(size*0.05), fill='white')

              # Camera lens (circle)
              lens_radius = int(cam_size * 0.25)
              draw.ellipse([
                  center_x - lens_radius,
                  center_y - lens_radius//2,
                  center_x + lens_radius,
                  center_y + lens_radius//2 + lens_radius//2
              ], fill='#333333')

              # Inner lens
              inner_radius = int(lens_radius * 0.7)
              draw.ellipse([
                  center_x - inner_radius,
                  center_y - inner_radius//2,
                  center_x + inner_radius,
                  center_y + inner_radius//2 + inner_radius//2
              ], fill='#666666')

              # Flash (retro style)
              flash_size = int(cam_size * 0.15)
              draw.ellipse([
                  center_x + cam_size//3,
                  center_y - cam_size//4,
                  center_x + cam_size//3 + flash_size,
                  center_y - cam_size//4 + flash_size
              ], fill='#FFD700')

              # Red recording dot
              if size > 80:
                  rec_size = int(size * 0.08)
                  draw.ellipse([
                      center_x - cam_size//3,
                      center_y - cam_size//4,
                      center_x - cam_size//3 + rec_size,
                      center_y - cam_size//4 + rec_size
                  ], fill='red')

              # Add "TCC" text for larger icons
              if size >= 180:
                  text_size = int(size * 0.08)
                  # Simple text at bottom
                  text_y = center_y + cam_size//2
                  draw.text((center_x, text_y), "TCC", fill='white', anchor='mt')

              img.save(filename)

          # Create Contents.json
          contents = {
              "images": [
                  {"size": "20x20", "idiom": "iphone", "filename": "icon-20@2x.png", "scale": "2x"},
                  {"size": "20x20", "idiom": "iphone", "filename": "icon-20@3x.png", "scale": "3x"},
                  {"size": "29x29", "idiom": "iphone", "filename": "icon-29@2x.png", "scale": "2x"},
                  {"size": "29x29", "idiom": "iphone", "filename": "icon-29@3x.png", "scale": "3x"},
                  {"size": "40x40", "idiom": "iphone", "filename": "icon-40@2x.png", "scale": "2x"},
                  {"size": "40x40", "idiom": "iphone", "filename": "icon-40@3x.png", "scale": "3x"},
                  {"size": "60x60", "idiom": "iphone", "filename": "icon-60@2x.png", "scale": "2x"},
                  {"size": "60x60", "idiom": "iphone", "filename": "icon-60@3x.png", "scale": "3x"},
                  {"size": "1024x1024", "idiom": "ios-marketing", "filename": "icon-1024.png", "scale": "1x"}
              ],
              "info": {"version": 1, "author": "xcode"}
          }

          with open('Contents.json', 'w') as f:
              json.dump(contents, f, indent=2)
          EOF
      - name: Create export options
        script: |
          cat > $CM_BUILD_DIR/export_options.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>6XNH7D52V6</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.mkyoung.timecapsulecamera</key>
              <string>TimeCapsuleCamera Dist Profile</string>
            </dict>
          </dict>
          </plist>
          EOF
      - name: Setup code signing
        script: |
          # Set up the keychain for certificates
          keychain initialize

          # Fetch signing certificates and profiles from App Store Connect
          # This uses the environment variables already configured in CodeMagic
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

          # Add certificates to keychain
          keychain add-certificates

          # Apply the provisioning profiles to the Xcode project
          xcode-project use-profiles

      - name: Build archive
        script: |
          # Use workspace if it exists (created by pod install), otherwise use project
          if [ -f "time_capsule_camera/TimeCapsuleCamera.xcworkspace/contents.xcworkspacedata" ]; then
            xcodebuild \
              -workspace "time_capsule_camera/TimeCapsuleCamera.xcworkspace" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -destination "generic/platform=iOS" \
              -archivePath $CM_BUILD_DIR/tcc.xcarchive \
              archive
          else
            xcodebuild \
              -project "$XCODE_PROJECT" \
              -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -destination "generic/platform=iOS" \
              -archivePath $CM_BUILD_DIR/tcc.xcarchive \
              archive
          fi
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/tcc.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist $CM_BUILD_DIR/export_options.plist
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - mkyoung23@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        # Using environment variables from ios_signing group
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

        # Automatically submit to TestFlight
        submit_to_testflight: true

        # Add to Beta Testers group (must exist in App Store Connect)
        beta_groups:
          - Beta Testers
