workflows:
  ios-build:
    name: iOS • TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mkyoung.timecapsulecamera
      xcode: latest

    scripts:
      - name: Build & archive
        script: |
          # project sits in the time_capsule_camera folder
          xcodebuild \
            -project "time_capsule_camera/TimeCapsuleCamera.xcodeproj" \
            -scheme "TimeCapsuleCamera" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/TimeCapsuleCamera.xcarchive" \
            CODE_SIGN_STYLE=Automatic \
            clean archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/TimeCapsuleCamera.xcarchive" \
            -exportPath "$CM_BUILD_DIR/ipa" \
            -exportOptionsPlist /tmp/xcodebuild_export_options.plist

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration        # uses the API-key vars you already added
        submit_to_testflight: true
      email:
        recipients:
          - m.k.young240@gmail.com
