workflows:
  ios-tcc:
    name: iOS - Time Capsule Camera
    instance_type: mac_mini_m2
    environment:
      vars:
        # PATHS
        XCODE_WORKSPACE: "time_capsule_camera/TimeCapsuleCamera.xcworkspace" 
        XCODE_SCHEME: "TimeCapsuleCamera"
        IOS_BUNDLE_ID: "com.mkyoung.timecapsulecamera"
      groups:
        - firebase_credentials

    # This downloads your certificates automatically
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

    scripts:
      - name: Install CocoaPods
        script: | 
          cd time_capsule_camera
          pod install

      - name: Set up code signing settings
        script: |
          # ⚡️ THIS IS THE FIX ⚡️
          # This command intelligently applies the profile ONLY to the app, not the pods.
          xcode-project use-profiles

      - name: Build archive
        script: |
          set -euo pipefail
          
          # Simplified command: We removed the lines that forced signing on Pods
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/TimeCapsuleCamera.xcarchive" \
            clean archive

      - name: Export IPA
        script: |
          set -euo pipefail
          EXPORT_PATH="$CM_BUILD_DIR/ipa"
          mkdir -p "$EXPORT_PATH"

          # We let CodeMagic detect the profile UUID automatically here
          cat <<EOF > exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>teamID</key><string>6XNH7D52V6</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$IOS_BUNDLE_ID</key><string>TimeCapsuleCamera Dist Profile</string>
            </dict>
          </dict>
          </plist>
          EOF

          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/TimeCapsuleCamera.xcarchive" \
            -exportPath "$EXPORT_PATH" \
            -exportOptionsPlist exportOptions.plist

      - name: Publish to Firebase App Distribution
        script: |
          npm install -g firebase-tools
          firebase appdistribution:distribute "$CM_BUILD_DIR/ipa/TimeCapsuleCamera.ipa" \
            --app "1:413771745824:ios:3203939db870ae52e08a45" \
            --groups "beta-testers" \
            --token "$FIREBASE_TOKEN"

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa