workflows:
  ios-tcc:
    name: iOS – Time Capsule Camera
    max_build_duration: 120
    # Updated configuration - ready for TestFlight
    environment:
      groups:
        - ios_signing
      vars:
        XCODE_PROJECT: "time_capsule_camera/TimeCapsuleCamera.xcodeproj"
        XCODE_SCHEME: "TimeCapsuleCamera"
        BUNDLE_ID: "com.mkyoung.timecapsulecamera"
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Generate placeholder app icons
        script: |
          cd time_capsule_camera/Assets.xcassets/AppIcon.appiconset
          convert -size 40x40 xc:"#4A90E2" "icon-20@2x.png"
          convert -size 60x60 xc:"#4A90E2" "icon-20@3x.png"
          convert -size 58x58 xc:"#4A90E2" "icon-29@2x.png"
          convert -size 87x87 xc:"#4A90E2" "icon-29@3x.png"
          convert -size 80x80 xc:"#4A90E2" "icon-40@2x.png"
          convert -size 120x120 xc:"#4A90E2" "icon-40@3x.png"
          convert -size 120x120 xc:"#4A90E2" "icon-60@2x.png"
          convert -size 180x180 xc:"#4A90E2" "icon-60@3x.png"
          convert -size 1024x1024 xc:"#4A90E2" "icon-1024.png"
      - name: Set up code signing
        script: |
          # Initialize keychain
          keychain initialize

          # Fetch signing files - now using @env: directly since group is loaded
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --issuer-id f94e54a5-8ebc-49c0-b581-1099125c304f \
            --key-id R9RRF25S4U \
            --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY \
            --type IOS_APP_STORE \
            --create

          # Add to keychain and configure Xcode
          keychain add-certificates
          xcode-project use-profiles
      - name: Resolve Swift packages
        script: xcodebuild -resolvePackageDependencies -project "$XCODE_PROJECT"
      - name: Build archive
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/tcc.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/tcc.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - mkyoung23@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: R9RRF25S4U
        issuer_id: f94e54a5-8ebc-49c0-b581-1099125c304f
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
