workflows:
  ios-tcc:
    name: iOS - Time Capsule Camera
    instance_type: mac_mini_m2
    environment:
      vars:
        # PATHS
        XCODE_WORKSPACE: "time_capsule_camera/TimeCapsuleCamera.xcworkspace" 
        XCODE_SCHEME: "TimeCapsuleCamera"
        IOS_BUNDLE_ID: "com.mkyoung.timecapsulecamera"
      groups:
        - firebase_credentials

    # We use your API Key to fetch the correct profile automatically
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

    scripts:
      - name: Install CocoaPods
        script: | 
          cd time_capsule_camera
          pod install

      - name: Fix Bundle ID and Sign
        script: |
          # 1. Force the Project to use the correct Bundle ID
          # This fixes the mismatch error!
          cd time_capsule_camera
          xcode-project build-settings --project TimeCapsuleCamera.xcodeproj --target TimeCapsuleCamera --set PRODUCT_BUNDLE_IDENTIFIER="$IOS_BUNDLE_ID"

          # 2. Fetch the matching profile from Apple
          keychain initialize
          app-store-connect fetch-signing-files "$IOS_BUNDLE_ID" --type IOS_APP_STORE --create
          app-store-connect add-certificates
          
          # 3. Apply it ONLY to the App (not the Pods)
          xcode-project use-profiles --project TimeCapsuleCamera.xcodeproj --target TimeCapsuleCamera

      - name: Build archive
        script: |
          set -euo pipefail
          
          # Build using the workspace with the fixed settings
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/TimeCapsuleCamera.xcarchive" \
            clean archive

      - name: Export IPA
        script: |
          set -euo pipefail
          EXPORT_PATH="$CM_BUILD_DIR/ipa"
          mkdir -p "$EXPORT_PATH"

          # Generate export options automatically
          xcode-project export-options-plist \
            --bundle-id "$IOS_BUNDLE_ID" \
            --output exportOptions.plist

          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/TimeCapsuleCamera.xcarchive" \
            -exportPath "$EXPORT_PATH" \
            -exportOptionsPlist exportOptions.plist

      - name: Publish to Firebase App Distribution
        script: |
          npm install -g firebase-tools
          firebase appdistribution:distribute "$CM_BUILD_DIR/ipa/TimeCapsuleCamera.ipa" \
            --app "1:413771745824:ios:3203939db870ae52e08a45" \
            --groups "beta-testers" \
            --token "$FIREBASE_TOKEN"

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa