workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - ios_signing
      vars:
        BUNDLE_ID: "com.mkyoung.timecapsulecamera"
        XCODE_PROJECT: "time_capsule_camera/TimeCapsuleCamera.xcodeproj"
        XCODE_SCHEME: "TimeCapsuleCamera"
      # Adjust if your scheme name is different
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-xcargs "CODE_SIGN_IDENTITY='Apple Distribution' OTHER_CODE_SIGN_FLAGS='--keychain=buildagent'" \
            --export-options-plist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    # publishing:
    #   app_store_connect:
    #     api_key: 68T7Y68ZWL
    #     api_key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    #     api_key_issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    #     key_encoding: base64 # Required if the API key is base64 encoded
    #     # Submit to TestFlight
    #     submit_to_testflight: true
    #     beta_groups:
    #       - "Testers"
    #     # Optional: Submit to App Store
    #     submit_to_app_store: false
