workflows:
  ios-tcc:
    name: iOS – Time Capsule Camera
    max_build_duration: 120
    # Updated configuration - ready for TestFlight
    environment:
      groups:
        - ios_signing
      vars:
        XCODE_PROJECT: "time_capsule_camera/TimeCapsuleCamera.xcodeproj"
        XCODE_SCHEME: "TimeCapsuleCamera"
        BUNDLE_ID: "com.mkyoung.timecapsulecamera"
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Generate placeholder app icons
        script: |
          # Install Pillow for image generation
          pip3 install --quiet pillow

          # Use Python to generate simple placeholder icons
          cd time_capsule_camera/Assets.xcassets/AppIcon.appiconset
          python3 << 'EOF'
          from PIL import Image

          # Define icon sizes
          sizes = [
              ("icon-20@2x.png", 40),
              ("icon-20@3x.png", 60),
              ("icon-29@2x.png", 58),
              ("icon-29@3x.png", 87),
              ("icon-40@2x.png", 80),
              ("icon-40@3x.png", 120),
              ("icon-60@2x.png", 120),
              ("icon-60@3x.png", 180),
              ("icon-1024.png", 1024)
          ]

          for filename, size in sizes:
              img = Image.new('RGB', (size, size), color='#4A90E2')
              img.save(filename)
          EOF
      - name: Set up code signing
        script: |
          set -e
          set -x

          echo "Setting up code signing..."
          echo "Bundle ID: $BUNDLE_ID"
          echo "Issuer ID: $APP_STORE_CONNECT_ISSUER_ID"
          echo "Key ID: $APP_STORE_CONNECT_KEY_IDENTIFIER"

          # Initialize keychain
          keychain initialize

          # Create a temporary file for the private key
          # Use echo -e to interpret escape sequences if present
          echo -e "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/api_key.p8

          # Verify key file was created correctly
          echo "Private key file size: $(wc -c < /tmp/api_key.p8) bytes"
          echo "Private key first line: $(head -n1 /tmp/api_key.p8)"
          echo "Private key line count: $(wc -l < /tmp/api_key.p8)"

          # Fetch signing files with explicit key file
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key /tmp/api_key.p8 \
            --type IOS_APP_STORE \
            --create

          # Clean up key file
          rm /tmp/api_key.p8

          # Add certificates to keychain
          keychain add-certificates

          # Configure Xcode project
          xcode-project use-profiles
      - name: Create export options
        script: |
          cat > $CM_BUILD_DIR/export_options.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>6XNH7D52V6</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.mkyoung.timecapsulecamera</key>
              <string>TimeCapsuleCamera Dist Profile</string>
            </dict>
          </dict>
          </plist>
          EOF
      - name: Resolve Swift packages
        script: xcodebuild -resolvePackageDependencies -project "$XCODE_PROJECT"
      - name: Build archive
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/tcc.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/tcc.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist $CM_BUILD_DIR/export_options.plist
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - mkyoung23@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        # Using environment variables from ios_signing group
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

        # Automatically submit to TestFlight
        submit_to_testflight: true

        # Add to Beta Testers group (must exist in App Store Connect)
        beta_groups:
          - Beta Testers
