workflows:
  ios-tcc:
    name: iOS – Time Capsule Camera
    max_build_duration: 120
    # Updated configuration - ready for TestFlight
    environment:
      groups:
        - ios_signing
      vars:
        XCODE_PROJECT: "time_capsule_camera/TimeCapsuleCamera.xcodeproj"
        XCODE_SCHEME: "TimeCapsuleCamera"
        BUNDLE_ID: "com.mkyoung.timecapsulecamera"
        APP_STORE_CONNECT_ISSUER_ID: f94e54a5-8ebc-49c0-b581-1099125c304f
        APP_STORE_CONNECT_KEY_IDENTIFIER: 68T7Y68ZWL
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Generate placeholder app icons
        script: |
          cd time_capsule_camera/Assets.xcassets/AppIcon.appiconset
          # Create simple placeholder icons for all required sizes
          convert -size 40x40 xc:"#4A90E2" "icon-20@2x.png"
          convert -size 60x60 xc:"#4A90E2" "icon-20@3x.png"
          convert -size 58x58 xc:"#4A90E2" "icon-29@2x.png"
          convert -size 87x87 xc:"#4A90E2" "icon-29@3x.png"
          convert -size 80x80 xc:"#4A90E2" "icon-40@2x.png"
          convert -size 120x120 xc:"#4A90E2" "icon-40@3x.png"
          convert -size 120x120 xc:"#4A90E2" "icon-60@2x.png"
          convert -size 180x180 xc:"#4A90E2" "icon-60@3x.png"
          convert -size 1024x1024 xc:"#4A90E2" "icon-1024.png"
          echo "Generated placeholder app icons"
      - name: Set up code signing
        script: |
          set -e
          set -x
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Resolve Swift packages
        script: xcodebuild -resolvePackageDependencies -project "$XCODE_PROJECT"
      - name: Build archive
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/tcc.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/tcc.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - mkyoung23@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        # Explicitly reference variables from ios_signing group
        api_key: $APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
