workflows:
  ios-release:
    name: ios Release
    environment:
      groups:
        - ios_signing
      vars:
        BUNDLE_ID: "com.mkyoung.timecapsulecamera"
        XCODE_PROJECT: "time_capsule_camera/TimeCapsuleCamera.xcodeproj"
        XCODE_SCHEME: "TimeCapsuleCamera"
    scripts:
      - name: Build & archive
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/TimeCapsuleCamera.xcarchive" \
            CODE_SIGN_STYLE=Automatic \
            clean archive
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APPSTORECONNECT_PRIVATE_KEY
        key_id: $APPSTORECONNECT_KEY_ID
        issuer_id: $APPSTORECONNECT_ISSUER_ID
        submit_to_testflight: true
