workflows:
  ios-build:
    name: iOS workflow
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mkyoung.timecapsulecamera
      vars:
        XCODE_PROJECT: "TimeCapsuleCamera.xcodeproj"
        XCODE_SCHEME: "TimeCapsuleCamera"
      xcode: latest

    scripts:
      - name: Set up iOS code signing
        script: |
          echo "Setting up automatic iOS code signing..."

      - name: Build iOS app
        script: |
          # Adjust folder path; no 'time_capsule_camera' subfolder
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
            clean archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/$XCODE_SCHEME.xcarchive" \
            -exportPath "$CM_BUILD_DIR/ipa" \
            -exportOptionsPlist /tmp/xcodebuild_export_options.plist

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa

    publishing:
      email:
        recipients:
          - m.k.young240@gmail.com
        notify:
          success: true
          failure: true
