workflows:
  ios-tcc:
    name: iOS – Time Capsule Camera
    max_build_duration: 120
    integrations:
      app_store_connect: TCC_ASC_KEY   # Name of your ASC API key in Codemagic
    environment:
      ios_signing:
        distribution_type: app_store    # or development / ad_hoc while testing
        bundle_identifier: com.yourco.tcc
    scripts:
      - name: Prepare signing & profiles
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$CM_BUNDLE_IDENTIFIER" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles    # CRITICAL so Xcode uses the fetched profiles
      - name: Resolve Swift packages
        script: xcodebuild -resolvePackageDependencies -project time_capsule_camera/TimeCapsuleCamera.xcodeproj
      - name: Build archive
        script: |
          xcodebuild \
            -project time_capsule_camera/TimeCapsuleCamera.xcodeproj \
            -scheme TimeCapsuleCamera \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/tcc.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/tcc.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
    publishing:
      app_store_connect:
        submit_to_testflight: true
        # set beta groups and release notes here if you like
