"""Interactive helper to generate Codemagic signing environment files.

This script walks through the minimum information that Codemagic needs to
produce a signed build for either ad-hoc (UDID-based) testing or TestFlight.
It collects the certificate, provisioning profile, bundle ID, and optional
App Store Connect API key, then writes everything into an `.env` style file so
you can `source` it locally or copy the values into Codemagic.

Usage:
    python scripts/setup_codmagic.py

You will be prompted for file paths and metadata. The script never uploads the
assets anywhere – it only reads them locally, encodes them as base64, and writes
them to the requested output file.
"""

from __future__ import annotations

import base64
import getpass
import os
from pathlib import Path
from textwrap import dedent


DEFAULT_OUTPUT = Path("codemagic.env.local")
DEFAULT_BUNDLE_ID = "com.mkyoung.timecapsulecamera"
DEFAULT_TEAM_ID = "6XNH7D52V6"


def prompt(text: str, *, default: str | None = None, secret: bool = False, allow_empty: bool = False) -> str:
    """Prompt the user for input, optionally providing a default value."""

    suffix = ""
    if default:
        suffix = f" [{default}]"
    full_prompt = f"{text}{suffix}: "

    while True:
        if secret:
            value = getpass.getpass(full_prompt)
        else:
            value = input(full_prompt)

        if not value:
            if default is not None:
                return default
            if allow_empty:
                return ""
            print("Please enter a value.")
            continue
        return value


def prompt_path(text: str) -> Path:
    """Prompt for a file path and ensure it exists."""

    while True:
        raw_value = prompt(text)
        path = Path(os.path.expanduser(raw_value)).resolve()
        if path.is_file():
            return path
        print(f"File not found: {path}")


def encode_file(path: Path) -> str:
    """Return a base64-encoded string for the given file."""

    data = path.read_bytes()
    return base64.b64encode(data).decode("utf-8")


def write_env_file(destination: Path, values: dict[str, str]) -> None:
    lines = ["# Generated by scripts/setup_codmagic.py"]
    for key, value in values.items():
        if value == "":
            continue
        # Avoid trailing spaces and wrap the value in double quotes to preserve newlines.
        escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
        lines.append(f"{key}=\"{escaped}\"")

    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    print(
        dedent(
            """
            === Codemagic signing helper ===

            This wizard will collect the certificate, provisioning profile, and
            optional App Store Connect API key required for Codemagic. When
            you're done, you'll have an `.env` file that you can `source`
            locally and mirror in Codemagic's `ios_signing` group.
            """
        ).strip()
    )

    output_path = prompt(
        "Where should we save the environment file?", default=str(DEFAULT_OUTPUT)
    )
    destination = Path(os.path.expanduser(output_path)).resolve()

    print(
        "\nHow do you plan to share the build? Choose `ad-hoc` for UDID-based installs "
        "or `app-store` to upload straight to TestFlight."
    )
    while True:
        export_method = prompt("Export method (ad-hoc/app-store)", default="ad-hoc").lower()
        if export_method in {"ad-hoc", "app-store"}:
            break
        print("Please type either 'ad-hoc' or 'app-store'.")

    print("\nLet's collect the signing assets.")
    cert_path = prompt_path("Path to your distribution .p12 certificate")
    cert_password = prompt(
        "Certificate password (leave blank if there isn't one)", secret=True, allow_empty=True
    )
    profile_path = prompt_path("Path to your provisioning profile (.mobileprovision)")

    bundle_id = prompt("Bundle identifier", default=DEFAULT_BUNDLE_ID)
    team_id = prompt("Apple Developer Team ID", default=DEFAULT_TEAM_ID)

    values: dict[str, str] = {
        "IOS_CERT_BASE64": encode_file(cert_path),
        "IOS_CERT_PASSWORD": cert_password,
        "IOS_PROFILE_BASE64": encode_file(profile_path),
        "IOS_BUNDLE_ID": bundle_id,
        "APPLE_TEAM_ID": team_id,
        "IOS_EXPORT_METHOD": export_method,
    }

    if export_method == "app-store":
        print(
            "\nTo upload to TestFlight you'll need an App Store Connect API key. "
            "If you don't have one yet, you can leave these blank and add them later."
        )
        key_path_input = prompt(
            "Path to your AuthKey .p8 file (leave blank to skip)", allow_empty=True
        )
        if key_path_input:
            key_path = Path(os.path.expanduser(key_path_input)).resolve()
            if not key_path.is_file():
                raise FileNotFoundError(f"App Store Connect key not found: {key_path}")
            values.update(
                {
                    "APP_STORE_CONNECT_API_KEY_BASE64": encode_file(key_path),
                    "APP_STORE_CONNECT_KEY_ID": prompt("App Store Connect Key ID"),
                    "APP_STORE_CONNECT_ISSUER_ID": prompt("App Store Connect Issuer ID"),
                }
            )
        else:
            print("Skipping API key for now. You can add it manually later when you're ready.")

    write_env_file(destination, values)

    print(
        dedent(
            f"""

            All set! Saved Codemagic variables to {destination}.

            Next steps:
              1. Review the file and keep it somewhere safe (it contains signing secrets).
              2. Run `source {destination}` locally, then `python scripts/check_codmagic_env.py` to verify.
              3. Copy the same values into Codemagic → Environment variables → `ios_signing` group.
              4. Start the `ios-build` workflow. The generated IPA/TestFlight build will install on
                 any device covered by your provisioning profile.

            Remember: refresh the provisioning profile whenever you add tester devices for ad-hoc
            builds, or switch the export method to `app-store` when you're ready to share via TestFlight.
            """
        ).strip()
    )


if __name__ == "__main__":
    main()
